[STLND-1950] - Version 0.1.2 - Added new message classes generated by updated CLI in version 0.0.16 - Added version check in pull request to develop to see if version already exists.If so it will be rejected, forcing the developer to increment version - Lint fixes

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -18,6 +18,7 @@ jobs:
         uses: actions/checkout@v4
         with:
           ref: ${{ github.event.pull_request.head.sha }}
+          fetch-depth: 0
 
       - name: Setup Python
         uses: actions/setup-python@v5
@@ -29,6 +30,16 @@ jobs:
           python -m pip install --upgrade pip
           pip install poetry
           poetry install --with dev --sync
+
+      - name: Check Version Against Existing Tags
+        run: |
+          VERSION=$(poetry version -s)  # Get version from pyproject.toml
+          if git tag --list | grep -q "^v$VERSION$"; then
+            echo "Error: Version v$VERSION already exists in tags. Please increment the version number."
+            exit 1
+          else
+            echo "Version v$VERSION is new, proceeding with checks."
+          fi
 
       - name: Check Formatting
         run: poetry run poe lint-check
